package com.flymaccin.demonicaistudio;
import org.json.*; import java.util.*;
final class FmeFunProject {
 static final int VERSION=1;
 static final class Clip { String id=UUID.randomUUID().toString(),type="audio",source=""; int track; long startTick,lengthTicks=UnifiedTransport.PPQ*4L,offsetFrames; float gain=1f,pan; boolean muted; }
 String name="Untitled FME Fun"; final UnifiedTransport transport=new UnifiedTransport(); final ArrayList<Clip> clips=new ArrayList<>(); final ArrayList<String> markers=new ArrayList<>();
 float timelineZoom=1f; float timelineScroll=0f; int verticalScroll=0;
 Clip addClip(int track,String type,String source,long tick,long length){Clip c=new Clip();c.track=track;c.type=type;c.source=source;c.startTick=Math.max(0,tick);c.lengthTicks=Math.max(1,length);clips.add(c);return c;}
 JSONObject toJson() throws JSONException { JSONObject r=new JSONObject();r.put("format","fmefun");r.put("version",VERSION);r.put("name",name);r.put("bpm",transport.bpm());r.put("tick",transport.tick());r.put("zoom",timelineZoom);r.put("scroll",timelineScroll);r.put("vScroll",verticalScroll);JSONArray a=new JSONArray();for(Clip c:clips){JSONObject j=new JSONObject();j.put("id",c.id);j.put("type",c.type);j.put("source",c.source);j.put("track",c.track);j.put("start",c.startTick);j.put("length",c.lengthTicks);j.put("offset",c.offsetFrames);j.put("gain",c.gain);j.put("pan",c.pan);j.put("muted",c.muted);a.put(j);}r.put("clips",a);r.put("markers",new JSONArray(markers));return r;}
 static FmeFunProject fromJson(String raw){FmeFunProject p=new FmeFunProject();try{JSONObject r=new JSONObject(raw);p.name=r.optString("name",p.name);p.transport.setBpm(r.optDouble("bpm",96));p.transport.seek(r.optLong("tick",0));p.timelineZoom=(float)r.optDouble("zoom",1);p.timelineScroll=(float)r.optDouble("scroll",0);p.verticalScroll=r.optInt("vScroll",0);JSONArray a=r.optJSONArray("clips");if(a!=null)for(int i=0;i<a.length();i++){JSONObject j=a.getJSONObject(i);Clip c=p.addClip(j.optInt("track"),j.optString("type"),j.optString("source"),j.optLong("start"),j.optLong("length",960));c.id=j.optString("id",c.id);c.offsetFrames=j.optLong("offset");c.gain=(float)j.optDouble("gain",1);c.pan=(float)j.optDouble("pan",0);c.muted=j.optBoolean("muted");}JSONArray m=r.optJSONArray("markers");if(m!=null)for(int i=0;i<m.length();i++)p.markers.add(m.optString(i));}catch(Exception ignored){}return p;}
}