package com.flymaccin.demonicaistudio;
import org.json.*; import java.util.*;
final class FmeFunProject {
 static final int VERSION=2, TRACKS=8, BUSES=4, PADS=16;
 static final class Clip { String id=UUID.randomUUID().toString(),type="audio",source=""; int track; long startTick,lengthTicks=UnifiedTransport.PPQ*4L,offsetFrames; float gain=1f,pan; boolean muted; String waveformKey=""; int waveformBuckets=0; }
 static final class SampleMap { int pad; String source=""; float pitch=0f,gain=1f,pan=0f; }
 String name="Untitled FME Fun"; final UnifiedTransport transport=new UnifiedTransport(); final ArrayList<Clip> clips=new ArrayList<>(); final ArrayList<String> markers=new ArrayList<>();
 final MidiClip midi=new MidiClip(); final DrumPattern drums=new DrumPattern(8,32); final MixerGraph mixer=new MixerGraph(TRACKS,BUSES); final ArrayList<SampleMap> samples=new ArrayList<>();
 float timelineZoom=1f,timelineScroll=0f; int verticalScroll=0;
 Clip addClip(int track,String type,String source,long tick,long length){Clip c=new Clip();c.track=track;c.type=type;c.source=source;c.startTick=Math.max(0,tick);c.lengthTicks=Math.max(1,length);clips.add(c);return c;}
 SampleMap sample(int pad){for(SampleMap s:samples)if(s.pad==pad)return s;SampleMap s=new SampleMap();s.pad=pad;samples.add(s);return s;}
 JSONObject toJson() throws JSONException {
  JSONObject r=new JSONObject();r.put("format","fmefun");r.put("version",VERSION);r.put("name",name);r.put("bpm",transport.bpm());r.put("tick",transport.tick());r.put("zoom",timelineZoom);r.put("scroll",timelineScroll);r.put("vScroll",verticalScroll);
  JSONArray a=new JSONArray();for(Clip c:clips){JSONObject j=new JSONObject();j.put("id",c.id);j.put("type",c.type);j.put("source",c.source);j.put("track",c.track);j.put("start",c.startTick);j.put("length",c.lengthTicks);j.put("offset",c.offsetFrames);j.put("gain",c.gain);j.put("pan",c.pan);j.put("muted",c.muted);j.put("waveformKey",c.waveformKey);j.put("waveformBuckets",c.waveformBuckets);a.put(j);}r.put("clips",a);r.put("markers",new JSONArray(markers));
  JSONArray notes=new JSONArray();for(MidiClip.Note n:midi.notes){JSONObject j=new JSONObject();j.put("start",n.startTick);j.put("duration",n.durationTicks);j.put("pitch",n.pitch);j.put("velocity",n.velocity);j.put("channel",n.channel);notes.put(j);}r.put("midiNotes",notes);
  JSONArray cc=new JSONArray();for(MidiClip.CC e:midi.cc){JSONObject j=new JSONObject();j.put("tick",e.tick);j.put("controller",e.controller);j.put("value",e.value);j.put("channel",e.channel);cc.put(j);}r.put("midiCC",cc);
  JSONObject d=new JSONObject();d.put("swing",drums.swing());JSONArray lanes=new JSONArray();for(int l=0;l<drums.laneCount();l++){JSONArray row=new JSONArray();for(int s=0;s<drums.stepCount();s++){DrumPattern.Step x=drums.step(l,s);JSONObject j=new JSONObject();j.put("on",x.active);j.put("velocity",x.velocity);j.put("probability",x.probability);j.put("shift",x.microShiftTicks);j.put("repeat",x.repeat);j.put("pitch",x.pitch);row.put(j);}lanes.put(row);}d.put("lanes",lanes);r.put("drums",d);
  r.put("mixer",mixerJson());JSONArray sm=new JSONArray();for(SampleMap s:samples){JSONObject j=new JSONObject();j.put("pad",s.pad);j.put("source",s.source);j.put("pitch",s.pitch);j.put("gain",s.gain);j.put("pan",s.pan);sm.put(j);}r.put("sampler",sm);return r;
 }
 private JSONObject mixerJson()throws JSONException{JSONObject m=new JSONObject();JSONArray cs=new JSONArray();for(MixerGraph.Channel c:mixer.channels)cs.put(channelJson(c));JSONArray bs=new JSONArray();for(MixerGraph.Channel c:mixer.buses)bs.put(channelJson(c));m.put("channels",cs);m.put("buses",bs);return m;}
 private static JSONObject channelJson(MixerGraph.Channel c)throws JSONException{JSONObject j=new JSONObject();j.put("gain",c.gain);j.put("pan",c.pan);j.put("mute",c.mute);j.put("solo",c.solo);j.put("recordArm",c.recordArm);j.put("monitor",c.monitor);j.put("bus",c.bus);JSONArray s=new JSONArray();for(float v:c.sends)s.put(v);j.put("sends",s);return j;}
 static FmeFunProject fromJson(String raw){FmeFunProject p=new FmeFunProject();try{JSONObject r=new JSONObject(raw);p.name=r.optString("name",p.name);p.transport.setBpm(r.optDouble("bpm",96));p.transport.seek(r.optLong("tick",0));p.timelineZoom=(float)r.optDouble("zoom",1);p.timelineScroll=(float)r.optDouble("scroll",0);p.verticalScroll=r.optInt("vScroll",0);
  JSONArray a=r.optJSONArray("clips");if(a!=null)for(int i=0;i<a.length();i++){JSONObject j=a.getJSONObject(i);Clip c=p.addClip(j.optInt("track"),j.optString("type"),j.optString("source"),j.optLong("start"),j.optLong("length",960));c.id=j.optString("id",c.id);c.offsetFrames=j.optLong("offset");c.gain=(float)j.optDouble("gain",1);c.pan=(float)j.optDouble("pan",0);c.muted=j.optBoolean("muted");c.waveformKey=j.optString("waveformKey","");c.waveformBuckets=j.optInt("waveformBuckets",0);}
  JSONArray ma=r.optJSONArray("markers");if(ma!=null)for(int i=0;i<ma.length();i++)p.markers.add(ma.optString(i));JSONArray ns=r.optJSONArray("midiNotes");if(ns!=null)for(int i=0;i<ns.length();i++){JSONObject j=ns.getJSONObject(i);p.midi.add(j.optLong("start"),j.optLong("duration",240),j.optInt("pitch",60),j.optInt("velocity",100),j.optInt("channel",0));}JSONArray cc=r.optJSONArray("midiCC");if(cc!=null)for(int i=0;i<cc.length();i++){JSONObject j=cc.getJSONObject(i);p.midi.addCC(j.optLong("tick"),j.optInt("controller"),j.optInt("value"),j.optInt("channel"));}
  JSONObject d=r.optJSONObject("drums");if(d!=null){p.drums.setSwing(d.optInt("swing"));JSONArray ls=d.optJSONArray("lanes");if(ls!=null)for(int l=0;l<Math.min(ls.length(),p.drums.laneCount());l++){JSONArray row=ls.optJSONArray(l);if(row!=null)for(int s=0;s<Math.min(row.length(),p.drums.stepCount());s++){JSONObject j=row.optJSONObject(s);if(j!=null){DrumPattern.Step x=p.drums.step(l,s);x.active=j.optBoolean("on");x.velocity=j.optInt("velocity",110);x.probability=j.optInt("probability",100);x.microShiftTicks=j.optInt("shift");x.repeat=j.optInt("repeat",1);x.pitch=(float)j.optDouble("pitch");}}}}
  readMixer(r.optJSONObject("mixer"),p.mixer);JSONArray sm=r.optJSONArray("sampler");if(sm!=null)for(int i=0;i<sm.length();i++){JSONObject j=sm.getJSONObject(i);SampleMap s=p.sample(j.optInt("pad"));s.source=j.optString("source");s.pitch=(float)j.optDouble("pitch");s.gain=(float)j.optDouble("gain",1);s.pan=(float)j.optDouble("pan");}
 }catch(Exception ignored){}return p;}
 private static void readMixer(JSONObject m,MixerGraph g){if(m==null)return;readChannels(m.optJSONArray("channels"),g.channels);readChannels(m.optJSONArray("buses"),g.buses);}
 private static void readChannels(JSONArray a,MixerGraph.Channel[] out){if(a==null)return;for(int i=0;i<Math.min(a.length(),out.length);i++){JSONObject j=a.optJSONObject(i);if(j==null)continue;MixerGraph.Channel c=out[i];c.gain=(float)j.optDouble("gain",1);c.pan=(float)j.optDouble("pan");c.mute=j.optBoolean("mute");c.solo=j.optBoolean("solo");c.recordArm=j.optBoolean("recordArm");c.monitor=j.optBoolean("monitor");c.bus=j.optInt("bus");JSONArray s=j.optJSONArray("sends");if(s!=null)for(int k=0;k<Math.min(s.length(),c.sends.length);k++)c.sends[k]=(float)s.optDouble(k);}}
}