package com.flymaccin.demonicaistudio;
import android.app.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;
public final class GameRooms {
 private GameRooms(){}
 public static View build(Activity a,String id){if("8bit".equals(id))return new ArcadeView(a,"8-BIT ISM",0);if("hyphyxels".equals(id))return new ArcadeView(a,"HY-PHYXELS: ARCADE INVASION",1);return new ArcadeView(a,"BAY CARNIVAL3 PARADE",2);}
 static final class ArcadeView extends View {Paint p=new Paint(1);int x=160,y=360,score=0,tick=0,mode;Random r=new Random(323);ArrayList<float[]> targets=new ArrayList<>();ArcadeView(Activity a,String title,int mode){super(a);this.mode=mode;setFocusable(true);for(int i=0;i<9;i++)targets.add(new float[]{80+r.nextInt(700),100+r.nextInt(650)});setContentDescription(title);}
 protected void onDraw(Canvas c){super.onDraw(c);c.drawColor(mode==0?Color.rgb(5,8,18):mode==1?Color.rgb(12,3,24):Color.rgb(18,5,12));p.setTypeface(Typeface.MONOSPACE);p.setTextSize(32);p.setColor(Color.WHITE);c.drawText(mode==0?"8-BIT ISM":mode==1?"HY-PHYXELS: ARCADE INVASION":"BAY CARNIVAL3 PARADE",28,48,p);p.setTextSize(18);c.drawText("SCORE "+score+"  •  TAP / DRAG TO MOVE  •  HIT THE PIXELS",28,78,p);for(float[]q:targets){p.setColor(mode==2?Color.MAGENTA:Color.CYAN);c.drawRect(q[0]-14,q[1]-14,q[0]+14,q[1]+14,p);}p.setColor(Color.YELLOW);c.drawCircle(x,y,22,p);if(mode==2){p.setColor(Color.rgb(255,120,30));for(int i=0;i<6;i++)c.drawCircle(80+i*120,760+(float)Math.sin((tick+i)*.3)*18,16,p);}tick++;postInvalidateDelayed(50);}
 public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()==0||e.getAction()==2){x=(int)e.getX();y=(int)e.getY();for(int i=targets.size()-1;i>=0;i--){float[]q=targets.get(i);if(Math.hypot(x-q[0],y-q[1])<55){targets.remove(i);score+=mode==1?25:10;targets.add(new float[]{50+r.nextInt(Math.max(60,getWidth()-100)),100+r.nextInt(Math.max(120,getHeight()-180))});}}invalidate();return true;}return true;}}
}
