package com.flymaccin.demonicaistudio;

import android.app.Activity;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.webkit.*;import android.widget.*;

public final class NativeRooms {
 private static final int BG=Color.rgb(8,9,14), WHITE=Color.rgb(239,241,248), MUTED=Color.rgb(157,163,180), PURPLE=Color.rgb(164,92,255);
 private NativeRooms(){}
 private static TextView text(Activity a,String s,int z){TextView v=new TextView(a);v.setText(s);v.setTextColor(WHITE);v.setTextSize(z);v.setPadding(16,12,16,12);return v;}
 private static LinearLayout base(Activity a,String title,String sub){LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(22,18,22,18);l.setBackgroundColor(BG);l.addView(text(a,title,26));TextView d=text(a,sub,14);d.setTextColor(MUTED);l.addView(d);return l;}
 public static View remote(Activity a){LinearLayout l=base(a,"POCKET POTNA REMOTE","Native FME control room. Pairing and room state stay in the Hub; third-party Remote Play is an explicit handoff.");String[] hubs={"PS5","Browser","Downloads","Apps","Files","Cloud","Settings"};for(String h:hubs){Button b=new Button(a);b.setText(h);b.setOnClickListener(v->{if(h.equals("PS5")){Intent i=a.getPackageManager().getLaunchIntentForPackage("com.playstation.remoteplay");if(i!=null)a.startActivity(i);else Toast.makeText(a,"PS Remote Play not installed",Toast.LENGTH_SHORT).show();}else Toast.makeText(a,h+" room surface active",Toast.LENGTH_SHORT).show();});l.addView(b);}return l;}
 public static View video(Activity a){LinearLayout l=base(a,"FME AI VIDEO GENERATOR","Cloud-backed generation room. Prompt and project controls live in the Hub; generation uses the declared LTX/ZeroGPU service.");EditText p=new EditText(a);p.setHint("Describe the video…");p.setTextColor(WHITE);p.setHintTextColor(MUTED);p.setMinLines(5);l.addView(p);Spinner ratio=new Spinner(a);ratio.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"16:9 Widescreen","9:16 Vertical"}));l.addView(ratio);Button refs=new Button(a);refs.setText("+ REFERENCE IMAGE");l.addView(refs);Button gen=new Button(a);gen.setText("GENERATE VIDEO");gen.setOnClickListener(v->Toast.makeText(a,"Generator engine migration connected next: LTX/ZeroGPU",Toast.LENGTH_LONG).show());l.addView(gen);return l;}
 public static View octop(Activity a){LinearLayout l=base(a,"OCTOP FME","Control-plane room • Agents • Memory • Knowledge • Plugins • Automation");EditText ep=new EditText(a);ep.setText("http://10.0.2.2:8088");ep.setTextColor(WHITE);l.addView(ep);Button c=new Button(a);c.setText("CONNECT CONTROL PLANE");l.addView(c);WebView w=new WebView(a);w.getSettings().setJavaScriptEnabled(true);w.getSettings().setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient());c.setOnClickListener(v->{String u=ep.getText().toString().trim();if(!u.startsWith("http"))u="http://"+u;w.loadUrl(u);});l.addView(w,new LinearLayout.LayoutParams(-1,0,1));return l;}
 public static View emulator(Activity a){LinearLayout l=base(a,"FME UNIVERSAL EMULATOR","Native emulator room migration target. ROM import, controller input, save states and libretro cores stay native.");Button pick=new Button(a);pick.setText("IMPORT ROM");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");a.startActivityForResult(i,9100);});l.addView(pick);l.addView(text(a,"16-core engine adapter is being moved behind this room. This is not an APK launcher.",14));return l;}
}
