package com.flymaccin.demonicaistudio;
final class StudioCommandController {
 final FmeFunProject project; final MixerGraph mixer; final CommandStack history=new CommandStack();
 StudioCommandController(FmeFunProject p,MixerGraph m){project=p;mixer=m;}
 void moveClip(FmeFunProject.Clip c,long tick,int track){final long ot=c.startTick;final int otr=c.track;final long nt=project.transport.snap(tick);final int ntr=Math.max(0,Math.min(mixer.channels.length-1,track));history.execute(new CommandStack.Command(){public void apply(){c.startTick=nt;c.track=ntr;}public void revert(){c.startTick=ot;c.track=otr;}public String label(){return "Move clip";}});}
 MidiClip.Note addNote(long tick,long duration,int pitch,int velocity,int channel){final MidiClip.Note[] holder=new MidiClip.Note[1];history.execute(new CommandStack.Command(){public void apply(){if(holder[0]==null)holder[0]=project.midi.add(tick,duration,pitch,velocity,channel);else project.midi.notes.add(holder[0]);}public void revert(){project.midi.remove(holder[0]);}public String label(){return "Add MIDI note";}});return holder[0];}
 void moveNote(MidiClip.Note n,long tick,int pitch){final long ot=n.startTick;final int op=n.pitch;final long nt=project.transport.snap(tick);history.execute(new CommandStack.Command(){public void apply(){project.midi.move(n,nt,pitch);}public void revert(){project.midi.move(n,ot,op);}public String label(){return "Move MIDI note";}});}
 void resizeNote(MidiClip.Note n,long duration){final long old=n.durationTicks;history.execute(new CommandStack.Command(){public void apply(){project.midi.resize(n,duration);}public void revert(){project.midi.resize(n,old);}public String label(){return "Resize MIDI note";}});}
 void toggleDrum(int lane,int step){history.execute(new CommandStack.Command(){public void apply(){project.drums.toggle(lane,step);}public void revert(){project.drums.toggle(lane,step);}public String label(){return "Toggle drum step";}});}
 void setGain(int ch,float value){final float old=mixer.channels[ch].gain;history.execute(new FloatCommand("Track gain",old,value,v->mixer.gain(ch,v)));}
 void setPan(int ch,float value){final float old=mixer.channels[ch].pan;history.execute(new FloatCommand("Track pan",old,value,v->mixer.pan(ch,v)));}
 void setSend(int ch,int bus,float value){final float old=mixer.channels[ch].sends[bus];history.execute(new FloatCommand("Send",old,value,v->mixer.send(ch,bus,v)));}
 void toggleArm(int ch){final boolean old=mixer.channels[ch].recordArm;history.execute(new CommandStack.Command(){public void apply(){mixer.channels[ch].recordArm=!old;}public void revert(){mixer.channels[ch].recordArm=old;}public String label(){return "Record arm";}});}
 void toggleMonitor(int ch){final boolean old=mixer.channels[ch].monitor;history.execute(new CommandStack.Command(){public void apply(){mixer.channels[ch].monitor=!old;}public void revert(){mixer.channels[ch].monitor=old;}public String label(){return "Monitor";}});}
 interface Setter{void set(float v);} static final class FloatCommand implements CommandStack.Command{final String n;final float a,b;final Setter s;FloatCommand(String n,float a,float b,Setter s){this.n=n;this.a=a;this.b=b;this.s=s;}public void apply(){s.set(b);}public void revert(){s.set(a);}public String label(){return n;}}
}