package com.flymaccin.demonicaistudio;
import android.content.Context;import android.graphics.*;import android.view.*;
final class TimelineTouchView extends View {
 interface Listener{void moveClip(FmeFunProject.Clip c,long tick,int track);void viewport(float zoom,float scroll);}
 final FmeFunProject project;final TimelineGestureState gesture=new TimelineGestureState();final ScaleGestureDetector scale;Listener listener;FmeFunProject.Clip drag;float downX,downY;long originalTick,previewTick;int originalTrack,previewTrack;
 TimelineTouchView(Context c,FmeFunProject p){super(c);project=p;gesture.zoom=p.timelineZoom;gesture.scrollX=p.timelineScroll;scale=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){gesture.pinch(d.getScaleFactor(),d.getFocusX());sync();invalidate();return true;}});}
 void setListener(Listener l){listener=l;}
 public boolean onTouchEvent(MotionEvent e){scale.onTouchEvent(e);if(scale.isInProgress())return true;float x=e.getX(),y=e.getY();int action=e.getActionMasked();
  if(action==MotionEvent.ACTION_DOWN){downX=x;downY=y;drag=hit(x,y);if(drag!=null){originalTick=drag.startTick;originalTrack=drag.track;previewTick=originalTick;previewTrack=originalTrack;}return true;}
  if(action==MotionEvent.ACTION_MOVE){if(drag!=null){previewTick=project.transport.snap(gesture.xToTick(x));previewTrack=Math.max(0,Math.min(project.mixer.channels.length-1,(int)((y+project.verticalScroll)/96)));drag.startTick=previewTick;drag.track=previewTrack;invalidate();}else{gesture.scroll(downX-x,(int)(downY-y));downX=x;downY=y;project.verticalScroll=gesture.scrollY;sync();invalidate();}return true;}
  if((action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL)&&drag!=null){FmeFunProject.Clip target=drag;long nt=previewTick;int tr=previewTrack;target.startTick=originalTick;target.track=originalTrack;drag=null;if(listener!=null&&action==MotionEvent.ACTION_UP)listener.moveClip(target,nt,tr);invalidate();return true;}return true;}
 private FmeFunProject.Clip hit(float x,float y){int tr=Math.max(0,(int)((y+project.verticalScroll)/96));long t=gesture.xToTick(x);for(FmeFunProject.Clip c:project.clips)if(c.track==tr&&t>=c.startTick&&t<=c.startTick+c.lengthTicks)return c;return null;}
 private void sync(){project.timelineZoom=gesture.zoom;project.timelineScroll=gesture.scrollX;if(listener!=null)listener.viewport(gesture.zoom,gesture.scrollX);}
 protected void onDraw(Canvas c){super.onDraw(c);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);c.drawColor(Color.rgb(8,9,14));c.save();c.translate(0,-project.verticalScroll);for(int t=0;t<project.mixer.channels.length;t++){p.setColor(Color.rgb(22,25,34));c.drawRect(0,t*96,getWidth(),t*96+1,p);}for(FmeFunProject.Clip clip:project.clips){float l=gesture.tickToX(clip.startTick),r=gesture.tickToX(clip.startTick+clip.lengthTicks),top=clip.track*96+8;p.setColor(clip.muted?Color.rgb(70,70,78):Color.rgb(112,74,190));c.drawRoundRect(l,top,r,top+80,10,10,p);p.setColor(Color.WHITE);p.setTextSize(22);c.drawText(clip.type,l+10,top+28,p);drawWave(c,p,clip,l,r,top);}c.restore();}
 private void drawWave(Canvas c,Paint p,FmeFunProject.Clip clip,float l,float r,float top){if(clip.waveformBuckets<=0)return;p.setColor(Color.argb(150,255,255,255));float mid=top+54;int bars=Math.min(32,clip.waveformBuckets);for(int i=0;i<bars;i++){float x=l+(r-l)*(i/(float)Math.max(1,bars-1));float h=4+(Math.abs((clip.waveformKey.hashCode()>>(i%16))&15)/15f)*17;c.drawLine(x,mid-h,x,mid+h,p);}}
}