package com.flymaccin.demonicaistudio;
import android.content.Context;import android.graphics.*;import android.view.*;
final class TimelineTouchView extends View {
 interface Listener{void moveClip(FmeFunProject.Clip c,long tick,int track);void viewport(float zoom,float scroll);}
 final FmeFunProject project;final TimelineGestureState gesture=new TimelineGestureState();final ScaleGestureDetector scale;Listener listener;FmeFunProject.Clip drag;float downX,downY;
 TimelineTouchView(Context c,FmeFunProject p){super(c);project=p;gesture.zoom=p.timelineZoom;gesture.scrollX=p.timelineScroll;scale=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){gesture.pinch(d.getScaleFactor(),d.getFocusX());sync();invalidate();return true;}});}
 void setListener(Listener l){listener=l;} public boolean onTouchEvent(android.view.MotionEvent e){scale.onTouchEvent(e);if(scale.isInProgress())return true;float x=e.getX(),y=e.getY();if(e.getAction()==0){downX=x;downY=y;drag=hit(x,y);return true;}if(e.getAction()==2){if(drag!=null){drag.startTick=project.transport.snap(gesture.xToTick(x));drag.track=Math.max(0,(int)(y/96));invalidate();}else{gesture.scroll(downX-x,(int)(downY-y));downX=x;downY=y;sync();invalidate();}return true;}if(e.getAction()==1&&drag!=null){if(listener!=null)listener.moveClip(drag,drag.startTick,drag.track);drag=null;return true;}return true;}
 private FmeFunProject.Clip hit(float x,float y){int tr=Math.max(0,(int)(y/96));long t=gesture.xToTick(x);for(FmeFunProject.Clip c:project.clips)if(c.track==tr&&t>=c.startTick&&t<=c.startTick+c.lengthTicks)return c;return null;}
 private void sync(){project.timelineZoom=gesture.zoom;project.timelineScroll=gesture.scrollX;if(listener!=null)listener.viewport(gesture.zoom,gesture.scrollX);}
 protected void onDraw(Canvas c){super.onDraw(c);Paint p=new Paint(1);p.setColor(Color.rgb(25,28,38));c.drawColor(Color.rgb(8,9,14));for(FmeFunProject.Clip clip:project.clips){float l=gesture.tickToX(clip.startTick),r=gesture.tickToX(clip.startTick+clip.lengthTicks),top=clip.track*96+8;p.setColor(Color.rgb(112,74,190));c.drawRoundRect(l,top,r,top+80,10,10,p);p.setColor(Color.WHITE);p.setTextSize(24);c.drawText(clip.type,l+10,top+30,p);}}}
