package com.flymaccin.demonicaistudio;
import android.app.*;import android.app.DownloadManager;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import java.util.*;
public final class UtilityRooms{
 private UtilityRooms(){} static final int BG=Color.rgb(8,9,14),FG=Color.rgb(243,241,255),M=Color.rgb(155,164,187);
 static LinearLayout base(Activity a,String h,String s){LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(22,18,22,18);l.setBackgroundColor(BG);l.addView(t(a,h,27,FG));l.addView(t(a,s,14,M));return l;} static TextView t(Activity a,String s,int z,int c){TextView v=new TextView(a);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(8,8,8,8);return v;} static Button b(Activity a,String s){Button b=new Button(a);b.setText(s);return b;}
 public static View agent(Activity a){LinearLayout l=base(a,"FME AGENT","Native command room • engineering workflow • PS5 integration • files • downloads • settings");String[] rows={"UMD / project specification reader","GitHub engineering workflow","Android build pipeline","Test + lint gates","Failure-log repair loop","Release/version ledger","Physical-phone QA handoff"};for(String x:rows)l.addView(t(a,"✓  "+x,16,FG));LinearLayout nav=new LinearLayout(a);Button dl=b(a,"DOWNLOADS");dl.setOnClickListener(v->a.startActivity(new Intent(DownloadManager.ACTION_VIEW_DOWNLOADS)));Button files=b(a,"FILES");files.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);a.startActivity(i);});Button set=b(a,"SETTINGS");set.setOnClickListener(v->a.startActivity(new Intent(Settings.ACTION_SETTINGS)));nav.addView(dl);nav.addView(files);nav.addView(set);l.addView(nav);l.addView(t(a,"PS5 native discovery/registration remains a pinned native-engine migration, not a Sony launcher.",13,M));return l;}
 public static View tv(Activity a){LinearLayout l=base(a,"DEMONIC TV","Resident media room • PS5 • Browser • Free TV • Local Video");LinearLayout src=new LinearLayout(a);for(String s:new String[]{"PS5","BROWSER","FREE TV","LOCAL VIDEO"}){Button x=b(a,s);x.setOnClickListener(v->Toast.makeText(a,"Source: "+s,Toast.LENGTH_SHORT).show());src.addView(x);}l.addView(src);FrameLayout stage=new FrameLayout(a);stage.setBackgroundColor(Color.BLACK);TextView screen=t(a,"DEMONIC TV RECEIVER SURFACE",20,FG);screen.setGravity(Gravity.CENTER);stage.addView(screen,new FrameLayout.LayoutParams(-1,-1));l.addView(stage,new LinearLayout.LayoutParams(-1,0,1));LinearLayout ctl=new LinearLayout(a);for(String s:new String[]{"DISCOVER","PAIR","CONNECT","DISCONNECT","DOCK","FULL","PiP"}){Button x=b(a,s);x.setOnClickListener(v->Toast.makeText(a,"TV "+s,Toast.LENGTH_SHORT).show());ctl.addView(x);}HorizontalScrollView hs=new HorizontalScrollView(a);hs.addView(ctl);l.addView(hs);return l;}
 public static View potna(Activity a){LinearLayout l=base(a,"POCKET POTNA","Native assistant room • conversation • command routing • FME tools");EditText input=new EditText(a);input.setHint("Talk to Pocket Potna…");input.setTextColor(FG);input.setHintTextColor(M);l.addView(input);TextView log=t(a,"Pocket Potna ready.",15,FG);l.addView(log,new LinearLayout.LayoutParams(-1,0,1));Button send=b(a,"SEND");send.setOnClickListener(v->{String q=input.getText().toString().trim();if(!q.isEmpty()){log.append("\n\nYOU: "+q+"\nPOTNA: Command captured locally. Connected AI provider routing belongs to the authorized service layer.");input.setText("");}});l.addView(send);return l;}
 public static View bayAuto(Activity a){LinearLayout l=base(a,"BAY AUTO RP","Native vehicle roleplay room • garage • cruise • jobs • reputation");TextView stat=t(a,"CAR: Bay Coupe  •  CASH: $500  •  REP: 0",16,FG);l.addView(stat);LinearLayout acts=new LinearLayout(a);final int[] cash={500},rep={0};for(String s:new String[]{"GARAGE","CRUISE","JOB","CAR MEET"}){Button x=b(a,s);x.setOnClickListener(v->{if(s.equals("JOB")){cash[0]+=125;rep[0]+=5;}else if(s.equals("CRUISE"))rep[0]+=1;else if(s.equals("CAR MEET"))rep[0]+=3;stat.setText("CAR: Bay Coupe  •  CASH: $"+cash[0]+"  •  REP: "+rep[0]);});acts.addView(x);}l.addView(acts);l.addView(t(a,"Drive loop is in-process. No external app launch.",13,M));return l;}
}
