package com.flymaccin.demonicaistudio;
import android.media.*;import java.io.*;
final class WavRecorder {
 private static final int SAMPLE_RATE=44100;private AudioRecord recorder;private AudioTrack monitorTrack;private Thread worker;private volatile boolean running;private volatile boolean monitor;private File output;private String lastError="";
 void setMonitoring(boolean enabled){monitor=enabled;}
 boolean start(File file){if(running)return false;try{int minimum=AudioRecord.getMinBufferSize(SAMPLE_RATE,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);int bufferSize=Math.max(minimum,SAMPLE_RATE/5)*2;recorder=new AudioRecord(MediaRecorder.AudioSource.MIC,SAMPLE_RATE,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,bufferSize);if(recorder.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("Microphone unavailable");if(monitor){monitorTrack=new AudioTrack.Builder().setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build()).setAudioFormat(new AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(SAMPLE_RATE).setChannelMask(AudioFormat.CHANNEL_OUT_MONO).build()).setBufferSizeInBytes(bufferSize).setTransferMode(AudioTrack.MODE_STREAM).build();monitorTrack.play();}output=file;lastError="";recorder.startRecording();running=true;worker=new Thread(()->capture(bufferSize),"fmefun-wav-recorder");worker.start();return true;}catch(Exception e){lastError=e.getClass().getSimpleName()+": "+e.getMessage();release();return false;}}
 File stop(){running=false;try{if(recorder!=null)recorder.stop();}catch(Exception ignored){}if(worker!=null)try{worker.join(1800);}catch(InterruptedException e){Thread.currentThread().interrupt();}release();return output!=null&&output.exists()&&output.length()>44?output:null;}
 boolean isRunning(){return running;}String getLastError(){return lastError;}
 private void capture(int bufferSize){long dataBytes=0;byte[] buffer=new byte[bufferSize];try(FileOutputStream stream=new FileOutputStream(output)){stream.write(new byte[44]);while(running){int count=recorder.read(buffer,0,buffer.length);if(count>0){stream.write(buffer,0,count);dataBytes+=count;if(monitorTrack!=null)monitorTrack.write(buffer,0,count);}}stream.flush();writeHeader(output,dataBytes);}catch(Exception e){lastError=e.getClass().getSimpleName()+": "+e.getMessage();if(output!=null)output.delete();}}
 private void release(){if(recorder!=null){recorder.release();recorder=null;}if(monitorTrack!=null){try{monitorTrack.stop();}catch(Exception ignored){}monitorTrack.release();monitorTrack=null;}worker=null;}
 private static void writeHeader(File file,long dataBytes)throws Exception{try(RandomAccessFile t=new RandomAccessFile(file,"rw")){t.seek(0);t.writeBytes("RIFF");writeIntLE(t,(int)(36+dataBytes));t.writeBytes("WAVEfmt ");writeIntLE(t,16);writeShortLE(t,(short)1);writeShortLE(t,(short)1);writeIntLE(t,SAMPLE_RATE);writeIntLE(t,SAMPLE_RATE*2);writeShortLE(t,(short)2);writeShortLE(t,(short)16);t.writeBytes("data");writeIntLE(t,(int)dataBytes);}}
 private static void writeIntLE(RandomAccessFile f,int v)throws Exception{f.write(v&255);f.write(v>>8&255);f.write(v>>16&255);f.write(v>>24&255);}private static void writeShortLE(RandomAccessFile f,short v)throws Exception{f.write(v&255);f.write(v>>8&255);}
}